# Generated by Django 5.0.4 on 2024-04-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaInteractiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('sala_interactiva', models.CharField(max_length=100)),
                ('imagen_relacionada_url', models.URLField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_interactivas/')),
            ],
        ),
    ]
